version: 2

image_and_dir: &image_and_dir
  docker:
    - image: circleci/node:7.10
  working_directory: ~/repo

jobs:
  build:
    <<: *image_and_dir
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: pwd
      - run: ls -la
      - run: npm install
      - run: ls -la
      - run: ls -la node_modules
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - .

  look:
    <<: *image_and_dir
    steps:
      - run: ls -la
      - attach_workspace:
          at: .
      - run: ls -la
      - run: ls -la node_modules

workflows:
  version: 2
  build_and_look:
    jobs:
      - build
      - look:
          requires:
            - build
