version: 2

defaults: &defaults
  docker:
    - image: circleci/node:10.6
  working_directory: ~/repo

# The traditional CircleCI jobs description includes restore_cache and
# save_cache to get performance gains across runs.  This is invalidated by
# using "npm ci", however, because it force-removes the "node_modules"
# directory before beginning the install.
#
# We do, however, make use of a CircleCI workspace to get persisted files
# between jobs along the workflow... such that later jobs do not also need to
# run "npm ci", they only need to attach_workspace.

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: cat package.json
      - run: npm ci
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  look:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace: { at: . }
      - run: cat package.json

  look2:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace: { at: . }
      - run: cat package.json

  bump_version:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace: { at: . }
      - run: cat package.json
      - run: |
            git config --global push.default simple
            git config --global user.email "npm@jaredreisinger.com"
            git config --global user.name "Automated Publisher"
      - run: npm version patch
      - run: cat package.json
      - run: git push --follow-tags
      - persist_to_workspace:
          root: .
          paths:
            - package.json
            - .git

  final:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace: { at: . }
      - run: cat package.json

workflows:
  version: 2
  build_and_look:
    jobs:
      - build
      - look:
          requires:
            - build
      - look2:
          requires:
            - build
      - bump_version:
          requires:
            - look
            - look2
          filters:
            branches:
              only: master
      - final:
          requires:
            - look
            - look2
            - bump_version
