version: 2

defaults: &defaults
  docker:
    - image: circleci/node:10.6
  working_directory: ~/repo

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: cat package.json
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      # - run: pwd
      # - run: ls -la
      # if we used `npm ci`, we wouldn't need/want the cache, as `ci`
      # force-installs everything.
      - run: npm install
      # - run: ls -la
      # - run: ls -la node_modules
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - .

  look:
    <<: *defaults
    steps:
      - attach_workspace: { at: . }
      - run: cat package.json

  look2:
    <<: *defaults
    steps:
      - attach_workspace: { at: . }
      - run: cat package.json

  bump_version:
    <<: *defaults
    steps:
      - attach_workspace: { at: . }
      - run: cat package.json
      - run: |
            git config --global push.default simple
            git config --global user.email "npm@jaredreisinger.com"
            git config --global user.name "Automated Publisher"
      - run: npm version patch
      - run: cat package.json
      - run: git push --follow-tags
      - persist_to_workspace:
          root: .
          paths:
            - package.json
            - .git

  final:
    <<: *defaults
    steps:
      - attach_workspace: { at: . }
      - run: cat package.json

workflows:
  version: 2
  build_and_look:
    jobs:
      - build
      - look:
          requires:
            - build
      - look2:
          requires:
            - build
      - bump_version:
          requires:
            - look
            - look2
          filters:
            branches:
              only: master
      - final:
          requires:
            - look
            - look2
            - bump_version
